Remove unused comparison "dunder" methods
These were originally intended for sorting by timestamp, but are not
being used in existing code for that purpose.

This is just dead code with type-ignores.
Without the ignores, they violate the Liscov substitution principle:

```
src/clickshare_temperature/log_archive.py:272: error: Argument 1 of "__gt__" is incompatible with supertype "builtins.tuple"; supertype defines the argument type as "tuple[datetime | str | int | None, ...]"  [override]
src/clickshare_temperature/log_archive.py:272: note: This violates the Liskov substitution principle
src/clickshare_temperature/log_archive.py:272: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
```